### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by egonw** [jmillanacosta/eNM-slides#3]
Slide 4:

- better references on the same slide (not sure if that is easy/hard with `beamer`)
- no need to say it's a logo (people can see it)

Slide 6:

- minimize the amount of text on slides (people cannot read and listen at the same time). use keywords

Slide 9, 14, 15, and 21:

- use whitespace efficiently. If you keep the text on the left (narrower), the image can go to the right and be larger (and better readable)

**Comment by jmillanacosta** [comment]
Thanks! Indeed the beamer settings need some rework to better fit the content in the slides.
